### ISSUE TITLE
well done

### ISSUE THREAD

**Issue by chenglinjava68** [Csaba79-coder/Spring5WebAppMadeByMe#1]

**Comment by Csaba79-coder** [comment]
thank you very much!

**Comment by chenglinjava68** [comment]
this is my github

https://github.com/chenglinjava68

**Comment by Csaba79-coder** [comment]
yes, thx, I already checked and started to follow you! come back later to your github, I jsut started this pet clinic project

**Comment by chenglinjava68** [comment]
Welcome more technical exchanges and communicate

**Comment by Csaba79-coder** [comment]
you can directly contact me on my email address csabavadasz79@gmail.com I'm quite new ... just study SpringFramework ... still not comportable with ... but I am just at the beginning of th road 👍
